# Generated by Django 5.2.6 on 2025-09-30 06:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(max_length=150, validators=[django.core.validators.MinLengthValidator(3, message='El nombre debe tener al menos 3 caracteres')])),
                ('email', models.EmailField(max_length=254, unique=True, validators=[django.core.validators.EmailValidator(message='Correo electrónico no válido')])),
                ('password', models.CharField(max_length=128, validators=[django.core.validators.MinLengthValidator(8, message='La contraseña debe tener mínimo 8 caracteres')])),
                ('fecha_nacimiento', models.DateField()),
                ('celular', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='El celular debe ser un número colombiano válido (10 dígitos, empieza con 3)', regex='^3\\d{9}$')])),
                ('telefono', models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator(message='El teléfono debe tener al menos 10 dígitos', regex='^\\d{10,}$')])),
                ('acepta_terminos', models.BooleanField(default=False)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
