# Generated by Django 5.2.6 on 2025-09-30 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Perritos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.URLField(help_text='URL del perrito')),
                ('titulo', models.CharField(max_length=200)),
                ('resumen', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('link_detalle', models.URLField(help_text='URL del detalle')),
            ],
        ),
    ]
